package com.nadvolod.order.domain;

import java.util.List;

/**
 * Output of the AI agent: a concise explanation + next actions.
 * Internal use only - customer messages are generated by CustomerMessageAgent.
 */
public record AgentAdvice(
    String summary,
    List<String> recommendedActions
) {}
